### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by holtwick** [holtwick/collect#1]
### Release 1.0

- [ ] Drag and drop in all directions
- [ ] Copy and paste (Clipboard)
- [x] Tags #2
- [ ] Import from Apple Notes
- [x] Scanner and OCR support like [PDFify](https://pdfify.app)
- [x] Export and sharing #25 #20 
- [x] Support platforms: macOS #3

### Release 1.x

- [ ] Todos #9 
- [ ] Support platforms: macOS, iOS #3 
- [ ] Better macOS integration like observed folders #26, share extension #25, Finder etc.

> Let me know in the comments what you like to see here
